# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.video_output = QtWidgets.QLabel(self.centralwidget)
        self.video_output.setObjectName("video_output")
        self.horizontalLayout_2.addWidget(self.video_output)
        self.zoom_effect = QtWidgets.QLabel(self.centralwidget)
        self.zoom_effect.setObjectName("zoom_effect")
        self.horizontalLayout_2.addWidget(self.zoom_effect)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grid = QtWidgets.QPushButton(self.centralwidget)
        self.grid.setObjectName("grid")
        self.horizontalLayout.addWidget(self.grid)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_location = QtWidgets.QPushButton(self.centralwidget)
        self.save_location.setObjectName("save_location")
        self.horizontalLayout.addWidget(self.save_location)
        self.img_save = QtWidgets.QPushButton(self.centralwidget)
        self.img_save.setObjectName("img_save")
        self.horizontalLayout.addWidget(self.img_save)
        self.video_save = QtWidgets.QPushButton(self.centralwidget)
        self.video_save.setObjectName("video_save")
        self.horizontalLayout.addWidget(self.video_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video_output.setText(_translate("MainWindow", "TextLabel"))
        self.zoom_effect.setText(_translate("MainWindow", "TextLabel"))
        self.grid.setText(_translate("MainWindow", "Show Grid"))
        self.save_location.setText(_translate("MainWindow", "Choose Save Location"))
        self.img_save.setText(_translate("MainWindow", "Save Image"))
        self.video_save.setText(_translate("MainWindow", "Save Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
